Feature: What the Door Does 

Scenario: simple case 
  Given Fido starts barking... 
  When I press remote button 
  Then The dog door opens 
  And Fido has gone outside... 
  And Fido's all done... 
