Feature: What the Door Does 

Scenario: Simple Path 
  Given Fido starts barking... 
  When I press remote button 
  Then The dog door "opens" 
  # Fido has gone outside... 
  # Fido's all done... 
  
Scenario: Remote Path 
  Given Fido starts barking... 
  When I press remote button 
  Then The dog door "opens" 
  # Fido has gone outside... 
  # Fido's all done... 
  When Wait a moment 
  Then The dog door "closes" 
  # ... but he's stuck outside! 
  # Fido starts barking... 
  # ...so Gina grabs the remote control 
  When I press remote button 
  Then The dog door "opens" 
  # Fido’s back inside... 
  
Scenario: Recognizer Path 
  Given Fido starts barking... 
  When Recognizer hearing a bark "Woof" 
  Then The dog door "opens" 
  # Fido has gone outside... 
  # Fido's all done... 
  When Wait a moment 
  Then The dog door "closes" 
  # ... but he's stuck outside! 
  # Fido starts barking... 
  When Recognizer hearing a bark "Woof" 
  Then The dog door "opens" 
  # Fido’s back inside... 
